name:                maf2-typelevel
version:             0.1.0.0
github:              "softwarelanguageslab/maf-hs"
license:             BSD-3-Clause
author:              "Software Languages Lab"
maintainer:          "coen.de.roover@vub.be"
copyright:           "2023 Software Languages Lab"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/softwarelanguageslab/maf-hs>

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- hashable
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Data.TypeLevel.HList
    - Data.TypeLevel.Pair
    - Data.TypeLevel.List
    - Data.TypeLevel.Struct

default-extensions:
  - TypeFamilies
  - TupleSections
  - TemplateHaskell
  - NamedFieldPuns
  - TypeOperators
  - InstanceSigs
  - DeriveGeneric
  - TypeApplications
  - StandaloneDeriving
  - ScopedTypeVariables
  - DataKinds
  - MultiParamTypeClasses
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving

tests:
  maf2-typelevel-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maf2-typelevel
